name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install prerequisites
      run: |
        sudo apt update
        sudo apt install -y g++-8
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

    - name: Install OpenCL driver for CPU
      run: sudo bash .github/scripts/install_intel_opencl.sh;

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: aplusb
      working-directory: ${{github.workspace}}/build
      run: ./aplusb

    - name: merge
      working-directory: ${{github.workspace}}/build
      run: ./merge
